name: dev-setup

services:
  ubuntu:
    image: ubuntu:24.04
    tty: true
    volumes:
      - ./:/files/
#    command: bash -i
    command: 
      # - cd /files
      - /files/dev-setup.sh
    environment:
      - IN_DOCKER=yes
      - GIT_USER=docker
      - GIT_EMAIL=docker@localhost
