name: Checksums
on:
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  test:
    if:  github.ref_name == 'master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checksums
        run: |
          ./update_checksums.sh
          CHANGES=$(git status -s)
          if [ -n "${CHANGES}" ] ; then 
            echo $CHANGES
            exit 1
          fi
